### ISSUE TITLE
[Feat] 스탬프 오브젝트 구현

### ISSUE THREAD

**Issue by KimSu-70** [KimSu-70/TeamProject#10]
### 개발 기능

- 개요
플레이어(큐브)의 면에 능력을 부여하는 오브젝트로 게임의 재미를 느끼게 할 요소 이며, 플레이어가 퍼즐을 풀거나
 이 게임에 몰입하게 할 수 있는 중요한 요소 중 하나 이다.

- 구현 계획
1. 큐브의 면에 접촉 했을 시 그 면이 능력을 가질 수 있게  구현 필요
2. 큐브의 스탬프 상태 구현과 밀접한 관련이 있어 구현 시 주의 필요

- 진행 상황
1. 스탬프 능력을 상태 패턴으로 구현
2. 각 능력 전이는 스탬프의 모양에 따라 달라진다
   - None: 없음
   - Red: 빨강
   - Blue: 파랑
   - Yellow: 노랑
3. 각 패턴들의 능력은 BaseState를 상속해서 사용

- [x] #25

**Comment by scv829** [comment]
진행 사항 내용 최신화

**Comment by KimSu-70** [comment]
진행 사항 내용 확인 완료
