### ISSUE TITLE
[Bug] 노란 스탬프 돌진시 엘베타일 위에서 공중에 떠있음.

### ISSUE THREAD

**Issue by cjfgk** [KimSu-70/TeamProject#104]
### 버그 리포트

- 버그 개요
![image](https://github.com/user-attachments/assets/b7764137-b5da-4115-bbdd-2d486f1d70fb)
돌진 시 해당위치에 멈춰섬 . 움직일순 있음 (32,AC)
- 발생 일자
24.11.01.
- 필요 조치
화이팅!

**Comment by KimSu-70** [comment]
해당 구간에서 발생하는 버그 확인 및 수정 완료 했습니다.
참고 바랍니다.
