### ISSUE TITLE
[Bug] 파란 스탬프 능력 사용 시 공중부양

### ISSUE THREAD

**Issue by cjfgk** [KimSu-70/TeamProject#107]
### 버그 리포트

- 버그 개요
스테이지 1과 동일
![image](https://github.com/user-attachments/assets/8bbcf879-01c0-4102-acad-a42cd532beb6)

- 발생 일자
24.11.1
- 필요 조치
1과 동일한 이유로 발생한거같음.

**Comment by KimSu-70** [comment]
버그 수정 완료 되었습니다.
내용 참고 바랍니다.
