### ISSUE TITLE
[Bug] 4스테이지 보라 스탬프로 관문을 비정상적으로 통과할 수 있는 문제

### ISSUE THREAD

**Issue by daseulkim2** [KimSu-70/TeamProject#150]
### 버그 리포트
![image](https://github.com/user-attachments/assets/384ebc04-df83-432f-bd57-8bd5dd5e9f2f)
![image](https://github.com/user-attachments/assets/b6928d81-84df-4bd3-8b91-cf1ffe28943b)
![image](https://github.com/user-attachments/assets/58f03b77-1cf6-49cb-9097-16d7860865f4)

- 버그 개요

4스테이지에 존재하는 모든 관문에서 스탬프를 찍어 관문을 열지 않고도
보라 스탬프의 능력을 이용하여 문에 끼어서 통과할 수 있는 문제 발견

- 발생 일자

- 필요 조치

**Comment by februarywind** [comment]
수정했습니다.
