### ISSUE TITLE
[Feat] 큐브 바닥 인식 및 낭떠러지 감지

### ISSUE THREAD

**Issue by KimSu-70** [KimSu-70/TeamProject#2]
### 개발 기능

- 개요
큐브의 원할한 이동 구현을 위해 바닥 인식 필요

- 구현 계획
1. 큐브의 바닥 인식 구현 필요
2. 낭떠러지 같은 지형 같은 경우 인식하게 구현 필요

- 진행 상황

~~1. 큐브의 바닥 인식 구현 필요~~
~~2. 낭떠러지 같은 지형 같은 경우 인식하게 구현 필요~~
---
- [x] 구현 완료

**Comment by februarywind** [comment]
완료 했습니다 확인 부탁 드립니다.
[커밋](https://github.com/KimSu-70/TeamProject/commit/57e63349c274c9e9fee7f94e1fca06c163de8be6)
