### ISSUE TITLE
[Bug] 스탬프 능력 작동 불일치

### ISSUE THREAD

**Issue by KimSu-70** [KimSu-70/TeamProject#35]
### 버그 리포트

- 버그 개요
1. 큐브의 한 면에서 첫 번째 스탬프 능력을 획득합니다.
2. 해당 면의 스탬프 능력은 정상적으로 발동됩니다.
3. 첫 번째 스탬프 능력을 얻은 채로 다른 면으로 스탬프 능력을 획득했을 때 정상적으로 획득됩니다.
4. 하지만 스탬프 능력을 사용하려고 하면 동작을 하지 않습니다.
5. 첫 번째 얻은 능력을 얻었던 큐브의 면은 스탬프 능력이 바뀌더라도 정상적으로 능력이 발동됩니다.
6. 동작하지 않던 면의 스탬프 능력을 먼저 획득하면, 해당 면의 스탬프 능력이 정상적으로 작동하는 증상이 있습니다.

- 발생 일자
2024.10.28일 20: 45분

- 필요 조치
1. 디버그 로그를 하나씩 체크 해 가면서 동작이 이상이 있는지 체크
2. 스탬프 능력 스크립트 디버그 중 문제로 추정되는 부분이 있어 주석 처리 진행 
   
###### 노란색 스탬프 아래의 내용 주석 처리
```C#
       // 이동 중이지 않고, 조건을 만족할 때만 마우스 왼쪽 키 입력을 확인
if (!isMoving &&
Mathf.Abs(playerTransform.eulerAngles.x) < xRotationThreshold &&
Mathf.Abs(playerTransform.eulerAngles.z) < zRotationThreshold &&
Input.GetMouseButtonDown(0))
```

###### 파란색 스탬프 아래의 내용 주석 처리
```C#
 // 플레이어 오브젝트의 X와 Z 회전이 0인지 확인 (허용 오차 포함)
 bool isXZero = Mathf.Abs(player.transform.eulerAngles.x) < rotationTolerance;
 bool isZZero = Mathf.Abs(player.transform.eulerAngles.z) < rotationTolerance;

 return isXZero && isZZero;
```

임시
주석 처리한 부분에서 이동 여부 및 회전 각도를 검증하는 로직이 정상 작동하지 않아,
특정 스탬프 능력 사용 시 호출되지 않거나 무시되는 문제가 있는 것으로 보입니다.

**Comment by februarywind** [comment]
확인했습니다. 
파란색 스탬프의 회전 확인은 필요 없는 부분 이였습니다.
큐브를 Y 축으로 회전 시킬 때  X, Z 에 따라 회전 값이 변하거나 하지 않기 때문입니다.
