### ISSUE TITLE
[Bug] 파란색 스탬프 회전 관련 버그

### ISSUE THREAD

**Issue by februarywind** [KimSu-70/TeamProject#49]
### 버그 리포트

- 버그 개요
1. 스탬프를 획득 후 회전 시 획득 스탬프가 사라지고 입력이 먹히지 않음
2. 해당 버그는 회전 코루틴 동작 시 x, z 회전 값을 0으로 바꿔 생기는 것으로 보임

- 발생 일자
2024-10-29 20:00

- 필요 조치

0으로 고정 시키는 값을 현재 
player.transform.eulerAngles = new Vector3(0, currentAngle, 0); // X와 Z를 0으로 설정되는 부분을

아래의 현재 포지션 값을 불러오게 수정
player.transform.eulerAngles = new Vector3(player.transform.eulerAngles.x, currentAngle, player.transform.eulerAngles.z); // X와 Z를 0으로 설정

**Comment by KimSu-70** [comment]
파란색 스탬프 회전 관련 버그 수정 완료 되었습니다
