### ISSUE TITLE
[Bug] 노란색 스탬프 능력 사용 시 리셋 타일 관련 버그

### ISSUE THREAD

**Issue by scv829** [KimSu-70/TeamProject#52]
### 버그 리포트

- 버그 개요
1. 노란색 스탬프를 획득 후 능력을 사용하여 이동하는데 리셋 타일을 뚫고 지나가서 초기화가 안됨
2. 아마 position을 직접 움직여서 트리거가 작동을 안하는 것으로 보임
- 발생 일자
2024-10-30 16:00
- 필요 조치
  -  직접 움직여서 부딪치면 리셋 타일이 작동하므로 리셋 타일 앞까지만 이동하게 변경
 ---
- [x] 구현 완료

**Comment by scv829** [comment]
필요 조치 내용 최신화

**Comment by KimSu-70** [comment]
내용 변경 확인 1 스테이지에서 테스트 진행 시 정상적으로 동작 확인
