### ISSUE TITLE
[Bug] 노란색 스탬프 능력 사용이 일부 오브젝트만 파괴

### ISSUE THREAD

**Issue by scv829** [KimSu-70/TeamProject#75]
### 버그 리포트

- 버그 개요
  - 노란색 스탬프 능력 사용이 일부 오브젝트만 파괴
  - 파괴를 해도 아직 벽이 있다고 인식(2024-10-31 16:00 발견)
- 발생 일자
2024-10-31 12:30
- 필요 조치
   - 오브젝트 파괴 관련 
       - 파괴되는 거리 수정 필요
       - 계산 순서가 잘못된 거 같으니 확인 후 수정
   - 벽 인식 관련
       - 파괴를 해도 아직 벽이 있어서 파괴가 아니라 다른 방법으로 구현

**Comment by KimSu-70** [comment]
버그 수정 완료 되었습니다.
2 스테이지에서 테스트 시 정상적으로 모든 오브젝트 파괴 확인 완료
