### ISSUE TITLE
[Bug] 리셋타일 적용안됨

### ISSUE THREAD

**Issue by cjfgk** [KimSu-70/TeamProject#77]
### 버그 리포트

- 버그 개요
리셋타일 적용안됨
![스크린샷 2024-10-31 173247](https://github.com/user-attachments/assets/18478737-f809-4ff7-b1d2-d6e15f3935ff)
![스크린샷 2024-10-31 173836](https://github.com/user-attachments/assets/3987f6c4-0fea-4e4c-a02d-1fc6d061ba72)

- 발생 일자
24.10.31.  17:42
- 필요 조치
(E,87~I,87) 리셋타일 작동안함. (M,73~N,73) 리셋타일 작동안함

**Comment by KimSu-70** [comment]
내용 확인 했습니다. 리셋 타일 부분 수정 완료 후
파일 재 공유 드리겠습니다. 참고 바랍니다.
