### ISSUE TITLE
[Bug] 공중에서 파란큐브 회전

### ISSUE THREAD

**Issue by cjfgk** [KimSu-70/TeamProject#78]
### 버그 리포트

- 버그 개요
![스크린샷 2024-10-31 173359](https://github.com/user-attachments/assets/9f702857-5ca4-4371-9ca8-46c8e6cb394e)

![스크린샷 2024-10-31 170938](https://github.com/user-attachments/assets/87255f1b-a9a5-4356-98d5-4d0dfafcf1d2)
![스크린샷 2024-10-31 170654](https://github.com/user-attachments/assets/a2a3e687-424a-447c-b081-b174d1b58468)
공중에서 제자리 회전 능력이 사용가능함. 사용 중 공중에서 떨어지지 않고 계속떠있음. 엘리베이터와 상호작용중  공중에서 능력 사용시 끼임 또는 기우는 버그 발생
- 발생 일자
10.31.  17:00
- 필요 조치
공중에서 제자리회전 기능 제한이 필요함.

**Comment by Thermal-Neuguris** [comment]
![스크린샷 2024-10-31 182310](https://github.com/user-attachments/assets/9a5f1979-9a0a-4f69-9a9c-06a7b077128a)
엘리베이터, 낙하 구간 등에서 큐브 회전 중 큐브가 사각형과 대응하지 않는 위치값인 때 착지하면 발동하는 버그로 보임

**Comment by februarywind** [comment]
수정 했습니다. 이제 공중 및 엘리베이터 이동 간 능력 사용이 제한됩니다.
