### ISSUE TITLE
[Bug] 노란큐브 능력

### ISSUE THREAD

**Issue by cjfgk** [KimSu-70/TeamProject#79]
### 버그 리포트

- 버그 개요
![스크린샷 2024-10-31 174042](https://github.com/user-attachments/assets/8c5472e8-effd-4fdb-8d37-624b1382c23e)
엘리베이터 작동과 동시에 능력 발동시 벽뚫
![스크린샷 2024-10-31 174009](https://github.com/user-attachments/assets/bd8fe480-b624-44fb-b1b5-906ee2e94cf5)
엘리베이터로 상승후 능력발동 제한
![스크린샷 2024-10-31 173948](https://github.com/user-attachments/assets/0b4cb6eb-b645-4114-9039-b6adcc4bdd01)
리셋타일 앞에서 능력발동 제한
![스크린샷 2024-10-31 173900](https://github.com/user-attachments/assets/5d399209-e081-461b-b9c1-e348205e26a8)
능력으로 터널벽 뚫음
![스크린샷 2024-10-31 173810](https://github.com/user-attachments/assets/af8287ef-a213-41a6-ba20-d77675bb239c)
물타일앞에서 능력발동 제한
- 발생 일자
10.31. 17:00
- 필요 조치
앞에 일반 타일이 있을경우에만 작동하는거같음..

**Comment by KimSu-70** [comment]
1차 버그 수정 완료 되었습니다. 작업 마무리 후 테스트 파일 공유 드리겠습니다.
