### ISSUE TITLE
[Bug] 노란 스탬프가 문을 뚫고 지나감

### ISSUE THREAD

**Issue by Thermal-Neuguris** [KimSu-70/TeamProject#80]
### 버그 리포트

- 버그 개요
![스크린샷 2024-10-31 184045](https://github.com/user-attachments/assets/55b8eac1-2522-4a8b-9181-5620667c5778)
![스크린샷 2024-10-31 184356](https://github.com/user-attachments/assets/28fe68c9-91b3-4549-8078-41cda4be2acc)
![스크린샷 2024-10-31 184335](https://github.com/user-attachments/assets/eff139c5-b23e-45f6-86eb-506edc46ae7b)
  - 노란색 스탬프가 문을 무시하고 발동되어 문을 지나침
   1) 노란색 스탬프 능력으로 문을 무시하고 지정 거리까지 돌진
   2) 문 앞에서 노란색 스탬프 능력 사용을 시도할 경우 스탬프 능력이 발동되어 문이 넘어가지는 경우가 있음. 누르는 횟수에 규칙성이 없는 것으로 보아, 손떨림에 의한 마우스 움직임이 차이를 만드는 것으로 보임
   3) Door 오브젝트의 모든 위치(door_frame_wood_double, door_wood_left, door_wood_right)에 해당 버그가 발생
   4) Door 오브젝트의 어떤 오브젝트와 겹쳐 있는 중에도 버그 발생 가능

- 발생 일자
2024-10-31 18:45

- 필요 조치
  - 직선 거리 앞 장애물 인식의 문제가 있어 보임. 정확히 직선이 아니면 장애물로 인식하지 않는 듯 함.

**Comment by KimSu-70** [comment]
버그 수정 완료 되었습니다.
문 통과가 안되게 수정하였습니다.
