### ISSUE TITLE
[Bug]노란 스탬프가 벽을 뚫고 지나감

### ISSUE THREAD

**Issue by Thermal-Neuguris** [KimSu-70/TeamProject#81]
### 버그 리포트

- 버그 개요
![스크린샷 2024-10-31 190046](https://github.com/user-attachments/assets/05822430-2889-400b-8446-36423e78e83c)
![스크린샷 2024-10-31 190100](https://github.com/user-attachments/assets/3958f973-0de9-40aa-8875-1f7ef33d9463)
![스크린샷 2024-10-31 190122](https://github.com/user-attachments/assets/edb84f5d-9407-4ec6-aa21-81f35871aaf4)
![스크린샷 2024-10-31 190157](https://github.com/user-attachments/assets/1798670f-c59e-459c-9c71-a3e319f06198)
  - 노란 스탬프를 벽 앞에서 사용할 경우 때때로 벽에 들어가짐
  - 벽의 종류에 상관이 없어 보임
  - 벽에서 벽으로 노란 스탬프 능력을 통해 계속 이동 가능
  - 정확하지 않을 수 있으나, 노란 스탬프로 못 움직이게 되는 순간이 생김

- 발생 일자
  - 2024-10-31 19:00

- 필요 조치
  - 노란 스탬프가 앞의 장애물을 체크할 때 '정확히 마우스 앞' 직선상의 장애물만 체크하는 것 같음. 확인 필요.

**Comment by KimSu-70** [comment]
버그 수정 완료되었습니다.
