### ISSUE TITLE
[Feat] 편의성 및 속도감 개선 희망사항

### ISSUE THREAD

**Issue by Thermal-Neuguris** [KimSu-70/TeamProject#82]
### 개발 기능

- 개요
  - 카메라 감도가 낮음
  - 연속으로 구를 때 카메라 들썩임이 심함
  - 경사로 속도가 느림
  - 큐브의 낙하 속도가 느림

- 구현 계획
  - 구현 여유가 있을 때 개발 진행
 
- 진행 상황
  - 희망사항 프로그래밍팀에 전달

**Comment by cjfgk** [comment]
큐브의 낙하 속도 증가 시 엘리베이터 하강속도도 같이 증가시켜야함.  먼저 내려와서 엘리베이터 안에 끼일 위험있음?

**Comment by februarywind** [comment]
카메라 들썩임을 수정 했습니다. 지금은 큐브가 너무 빨라서 그런 면도 있을지도
카메라 감도, 경사로 속도는 간편하게 설정 할 수 있습니다. 원하는 속도 알려주세요
낙하 속도는 내일 건드려 보겠습니다.
