### ISSUE TITLE
[Bug] Stage1_블록 뚫림 

### ISSUE THREAD

**Issue by Qui-0** [KimSu-70/TeamProject#88]
### 버그 리포트

- 버그 개요
Stage1 첫 엘리베이터 타일 정면 블록 뚫림  
![image](https://github.com/user-attachments/assets/fd935d23-5466-4ffa-9be0-75e190ad6a7a)

- 발생 일자
24/11/01

- 필요 조치
충돌 판정 생성 필요.

**Comment by februarywind** [comment]
레이어 설정을 안 해서 생기는 문제 같습니다.

**Comment by KimSu-70** [comment]
해당 내용 수정 완료 되었습니다.
