### ISSUE TITLE
[Bug] 노란 스탬프가 돌진 중 마주친 스탬프를 획득/큐브의 엉뚱한 면에 배치

### ISSUE THREAD

**Issue by Thermal-Neuguris** [KimSu-70/TeamProject#89]
### 버그 리포트

- 버그 개요
![스크린샷 2024-10-31 190339](https://github.com/user-attachments/assets/bdc6037c-de6c-472f-8885-e44ed9e2e64c)
![스크린샷 2024-10-31 190350](https://github.com/user-attachments/assets/60100f34-0382-4059-84b7-9ef2052b79bf)
  - 노란 스탬프로 파랑 스탬프 지역 위를 능력으로 지나갔는데 파랑 스탬프가 큐브 정면 기준 전면, 후면에 부착됨
  - 정확한 조건 확인 실패
  - 상황 상세 : 테스트를 위해 큐브를 막바지 경사로 아래쪽에 리스폰시킨 뒤 엘리베이터로 돌아가 노란 스탬프를 큐브 상면, 하면에 배치 후 경사로측 -> 파랑 스탬프 방향으로 능력 사용하였을 때 발견함

- 발생 일자
  - 2024-10-31 18:30
- 필요 조치
  - 버그 재발견 시 정확한 원인 파악 후 대처

**Comment by KimSu-70** [comment]
버그 수정 완료
노란 스탬프 이동 부분을 개선 하였습니다.
내용 참고 바랍니다.
